FATAL Flags parsing error: Unknown command line flag 'test_data_split'. Did you mean: eval_data_split ?
Pass --helpshort or --helpfull to see help on flags.
I0105 22:43:30.091208 140736542172096 main.py:337] Saved model parameters:
I0105 22:43:30.091521 140736542172096 main.py:339] 0: model_type=lr
I0105 22:43:30.091583 140736542172096 main.py:339] 1: input_size=256
I0105 22:43:30.091632 140736542172096 main.py:339] 2: rnn_hidden_size=256
I0105 22:43:30.091677 140736542172096 main.py:339] 3: use_attention=False
I0105 22:43:30.091721 140736542172096 main.py:339] 4: rnn_type=lstm
I0105 22:43:30.091763 140736542172096 main.py:339] 5: rnn_layers=1
I0105 22:43:30.091805 140736542172096 main.py:339] 6: rnn_dropout=0.0
I0105 22:43:30.091870 140736542172096 main.py:339] 7: rnn_bidirectional=False
I0105 22:43:30.091914 140736542172096 main.py:339] 8: standardize=True
I0105 22:43:30.091958 140736542172096 main.py:339] 9: block_size=6
I0105 22:43:30.092000 140736542172096 main.py:339] 10: history_window=8
I0105 22:43:30.092041 140736542172096 main.py:339] 11: prediction_window=2
I0105 22:43:30.092083 140736542172096 main.py:339] 12: target_label=death
I0105 22:43:30.092125 140736542172096 main.py:339] 13: data_dir=./data
I0105 22:43:30.092166 140736542172096 main.py:339] 14: lr_pooling=mean
I0105 22:43:30.092217 140736542172096 main.py:523] Mode: Inference
I0105 22:43:30.092270 140736542172096 main.py:208] 0: code/main.py
I0105 22:43:30.092313 140736542172096 main.py:208] 1: --phase=inference
I0105 22:43:30.092355 140736542172096 main.py:208] 2: --batch_size=128
I0105 22:43:30.092396 140736542172096 main.py:208] 3: --eval_data_split=val
I0105 22:43:30.092437 140736542172096 main.py:208] 4: --eval_dataset_size=0
I0105 22:43:30.092478 140736542172096 main.py:208] 5: --checkpoint_dir=./experiments
I0105 22:43:30.092519 140736542172096 main.py:208] 6: --experiment_name=death_trial
I0105 22:43:31.245350 140736542172096 dataset.py:115] Number of admissions: 4329
I0105 22:43:31.245760 140736542172096 dataset.py:116] Preprocess dataset with block size of 6
I0105 22:43:58.465007 140736542172096 main.py:337] Saved model parameters:
I0105 22:43:58.465434 140736542172096 main.py:339] 0: model_type=lr
I0105 22:43:58.465530 140736542172096 main.py:339] 1: input_size=256
I0105 22:43:58.465611 140736542172096 main.py:339] 2: rnn_hidden_size=256
I0105 22:43:58.465687 140736542172096 main.py:339] 3: use_attention=False
I0105 22:43:58.465794 140736542172096 main.py:339] 4: rnn_type=lstm
I0105 22:43:58.465875 140736542172096 main.py:339] 5: rnn_layers=1
I0105 22:43:58.465950 140736542172096 main.py:339] 6: rnn_dropout=0.0
I0105 22:43:58.466027 140736542172096 main.py:339] 7: rnn_bidirectional=False
I0105 22:43:58.466102 140736542172096 main.py:339] 8: standardize=True
I0105 22:43:58.466176 140736542172096 main.py:339] 9: block_size=6
I0105 22:43:58.466248 140736542172096 main.py:339] 10: history_window=8
I0105 22:43:58.466319 140736542172096 main.py:339] 11: prediction_window=2
I0105 22:43:58.466388 140736542172096 main.py:339] 12: target_label=death
I0105 22:43:58.466457 140736542172096 main.py:339] 13: data_dir=./data
I0105 22:43:58.466526 140736542172096 main.py:339] 14: lr_pooling=mean
I0105 22:43:58.466611 140736542172096 main.py:523] Mode: Inference
I0105 22:43:58.466701 140736542172096 main.py:208] 0: code/main.py
I0105 22:43:58.466773 140736542172096 main.py:208] 1: --phase=inference
I0105 22:43:58.466845 140736542172096 main.py:208] 2: --batch_size=128
I0105 22:43:58.466912 140736542172096 main.py:208] 3: --eval_data_split=val
I0105 22:43:58.466998 140736542172096 main.py:208] 4: --eval_dataset_size=0
I0105 22:43:58.467071 140736542172096 main.py:208] 5: --checkpoint_dir=./experiments
I0105 22:43:58.467144 140736542172096 main.py:208] 6: --experiment_name=death_trial
I0105 22:44:00.358732 140736542172096 dataset.py:115] Number of admissions: 4329
I0105 22:44:00.359394 140736542172096 dataset.py:116] Preprocess dataset with block size of 6
I0105 22:44:05.643215 140736542172096 dataset.py:122] Preprocess completed.
I0105 22:44:05.643378 140736542172096 dataset.py:127] Resample dataset...
I0105 22:44:05.643472 140736542172096 dataset.py:164] Number of instances in labels: 4329
I0105 22:44:05.889733 140736542172096 dataset.py:197] Dataset use default size: 1384
I0105 22:44:05.890127 140736542172096 dataset.py:198]   Use all 692 positive samples
I0105 22:44:05.890259 140736542172096 dataset.py:200]   Randomly choose 692 negative samples from 136714 candidates
I0105 22:44:05.899136 140736542172096 dataset.py:129] Resample dataset completed!
I0105 22:44:10.269898 140736542172096 dataset.py:138] Feature shape for PCA: (4329, 4010)
I0105 22:44:10.315052 140736542172096 main.py:249] Total number of checkpoints: 5
I0105 22:44:10.315250 140736542172096 main.py:251] 0: checkpoint_epoch001.model
I0105 22:44:10.315346 140736542172096 main.py:251] 1: checkpoint_epoch002.model
I0105 22:44:10.315428 140736542172096 main.py:251] 2: checkpoint_epoch003.model
I0105 22:44:10.315502 140736542172096 main.py:251] 3: checkpoint_epoch004.model
I0105 22:44:10.315570 140736542172096 main.py:251] 4: checkpoint_epoch005.model
I0105 22:44:10.320124 140736542172096 main.py:258] Load model from: ./experiments/death_trial/checkpoint_epoch001.model
I0105 22:44:10.320648 140736542172096 main.py:262] Initializatoin complete. Start inference.
I0105 22:44:12.815615 140736542172096 main.py:277] Progress: 10 / 11
Traceback (most recent call last):
  File "code/main.py", line 531, in <module>
    app.run(main)
  File "/Users/tianyicui/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/tianyicui/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "code/main.py", line 524, in main
    inference(configs)
  File "code/main.py", line 279, in inference
    utilities.update_metrics(metrics, checkpoint_name, y_true, y_score)
TypeError: update_metrics() missing 3 required positional arguments: 'phase', 'summary_writer', and 'step'
I0105 22:44:41.226809 140736542172096 dataset.py:122] Preprocess completed.
I0105 22:44:41.228845 140736542172096 dataset.py:127] Resample dataset...
I0105 22:44:41.229237 140736542172096 dataset.py:164] Number of instances in labels: 4329
I0105 22:44:41.474349 140736542172096 dataset.py:197] Dataset use default size: 1384
I0105 22:44:41.474628 140736542172096 dataset.py:198]   Use all 692 positive samples
I0105 22:44:41.474709 140736542172096 dataset.py:200]   Randomly choose 692 negative samples from 136714 candidates
I0105 22:44:41.482495 140736542172096 dataset.py:129] Resample dataset completed!
I0105 22:44:48.511410 140736542172096 dataset.py:138] Feature shape for PCA: (4329, 4010)
I0105 22:44:48.564029 140736542172096 main.py:249] Total number of checkpoints: 5
I0105 22:44:48.564259 140736542172096 main.py:251] 0: checkpoint_epoch001.model
I0105 22:44:48.564337 140736542172096 main.py:251] 1: checkpoint_epoch002.model
I0105 22:44:48.564389 140736542172096 main.py:251] 2: checkpoint_epoch003.model
I0105 22:44:48.564439 140736542172096 main.py:251] 3: checkpoint_epoch004.model
I0105 22:44:48.564486 140736542172096 main.py:251] 4: checkpoint_epoch005.model
I0105 22:44:48.566261 140736542172096 main.py:258] Load model from: ./experiments/death_trial/checkpoint_epoch001.model
I0105 22:44:48.566740 140736542172096 main.py:262] Initializatoin complete. Start inference.
I0105 22:44:50.623131 140736542172096 main.py:277] Progress: 10 / 11
Traceback (most recent call last):
  File "code/main.py", line 531, in <module>
    app.run(main)
  File "/Users/tianyicui/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/tianyicui/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "code/main.py", line 524, in main
    inference(configs)
  File "code/main.py", line 279, in inference
    utilities.update_metrics(metrics, checkpoint_name, y_true, y_score)
TypeError: update_metrics() missing 3 required positional arguments: 'phase', 'summary_writer', and 'step'
